### ISSUE TITLE
"$value is not allowed here": Error message is displayed even with correct select options

### ISSUE THREAD

**Issue by yhabteab** [Icinga/ipl-html#47]
## Describe the bug

During my tests for the [enhanced dashboards](https://github.com/Icinga/icingaweb2/pull/4323), this error message pops up upon the dashboards belonging a specific home once I switch to another home even though the options were reseted just basing on the selected home. Instead, a dashboard that was selected in the previous home shows up as not allowed value for the newer home before even loading the new options and it took me a very long time to find out the reason. And according to my current state, I can say that this is not due to the code on my end but rather to the ``setValue()`` method. To make it clearer I have included a few screenshots.

## Screenshots

First active dashboard home ``Transactions`` and selected dashboard ``Current Incidents``.

<img width="1090" alt="Bildschirmfoto 2021-05-25 um 11 48 35" src="https://user-images.githubusercontent.com/57616252/119477353-2c67d380-bd4f-11eb-9aa6-1984aa1fe4fb.png">

Now switch to another home ``Banking``.

<img width="1090" alt="Bildschirmfoto 2021-05-25 um 11 51 43" src="https://user-images.githubusercontent.com/57616252/119477810-97190f00-bd4f-11eb-95fd-12ac3db2cfaf.png">

As you can see, the ``setValue()`` method is either called before the new options are set, remembers the previous active value somehow, or is not necessary to print this error message at all.

**Comment by nilmerg** [comment]
Ha! I already expected this to be raised up here. That's the same as https://github.com/Icinga/icingaweb2/issues/1084 which lead to https://github.com/Icinga/icingaweb2/commit/9596b4fdf75188ee3470aa22a0ad3186fd6548aa.
