### ISSUE TITLE
`Attributes::Add()` should use setValue() if the attribute already exists and the value is bool

### ISSUE THREAD

**Issue by sukhwinder33445** [Icinga/ipl-html#79]
When an element already has an attribute with a `boolean` value (like `required`, `disabled`), adding the same attribute again will result in incorrect output. Example: Attribute `disabled` (Expected output:` disabled`, current output: `disabled="1 1"`).

## Expected Behavior:
https://github.com/Icinga/ipl-html/blob/0285e952c9c6bd9266c0765ad324e00991814230/src/Attributes.php#L273
When the attribute has a boolean value, `setValue()` should be used instead.

**Comment by nilmerg** [comment]
While I understand the reason for expecting this (The attributes knows it has a boolean value so can differentiate), I would not expect a call to `addValue` to magically be diverted to `setValue`. If I want to add a value, it should be *added*, no matter what.

Where I'd adjust things is where `addValue` is called in the first place. And that's where?

**Comment by nilmerg** [comment]
> And that's where?

Or `Attributes::add`, in this case.

**Comment by sukhwinder33445** [comment]
Yes, I understand. Then it is good the ways it is.
When I implemented `RadioElement`, I called `addAttribute()` before [here](https://github.com/Icinga/ipl-html/blob/e08c13e955bfb9df42d0635e3212bb5f19b425d8/src/FormElement/RadioElement.php#L54). That's why I noticed it.

**Comment by nilmerg** [comment]
I see ;)
